function answer = editdialog(CurrentPoint,LastInput)
    
    d = dialog('Position',[CurrentPoint(1) CurrentPoint(2) 150 150]);
    % opening text
    txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[1 130 150 15],...
    'FontSize',10,...
    'Fontweight','Bold',...
    'String',{'press Enter to confirm'},...
    'HorizontalAlignment','Center');
    % neuron idx input
    txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[1 110 150 15],...
    'FontSize',8,...
    'String',{'Input neuron index'},...
    'HorizontalAlignment','Center');
    edit = uicontrol('Parent',d,...
    'Style','edit',...
    'Position',[30 85 100 25],...
    'String',LastInput(1),...
    'Callback',@edit_callback,...
    'KeyReleaseFcn',@edit_KeyReleaseFcn);
    % choose if change same indexes throughout all slices in this volume
    txt = uicontrol('Parent',d,...
    'Style','text',...
    'Position',[1 55 150 15],...
    'FontSize',8,...
    'String',{'change all the same indexes?'},...
    'HorizontalAlignment','Center');
    
    switch LastInput(2)
    case "only this one"
        popupValue=1;
    case "all the same"
        popupValue=2;
    case "this one and below"
        popupValue=3;
    case "this one and above"
        popupValue=4;
    otherwise
        popupValue=1;
    end
    
    popup = uicontrol('Parent',d,...
            'Style','popup',...
            'Position',[1 30 149 25],...
            'String',{"only this one";"all the same";"this one and below";"this one and above"},...
            'Value',popupValue,...
            'Callback',@popup_callback,...
            'KeyReleaseFcn',@edit_KeyReleaseFcn); 
    uicontrol(edit);  
    answer = LastInput;
% Wait for d to close before running to completion
    uiwait(d);
    function edit_callback(edit,event)
      answer(1) = edit.String;      
    end
    function popup_callback(popup,event)
        idx = popup.Value;
        popup_items = popup.String;
        answer(2) = convertCharsToStrings(popup_items{idx});
     end
    function edit_KeyReleaseFcn(edit,event)
        f=edit.Parent;
        % if user pressed Enter
        if f.CurrentCharacter==13 % Enter is 13
            delete(gcf);
        end
    end     
        
end